### ISSUE TITLE
Why not use C # to completely rewrite C Native code ?

### ISSUE THREAD

**Issue by MIAIONE** [sgrottel/EverythingSearchClient#9]
I think in most cases, nuget and many package authors choose P / Invoke and dll because they don 't want to carry exe installer or use IPC. Can I implement / support a fully managed version of everything ?

**Comment by sgrottel** [comment]
Sorry, for my late reply.

To my understanding, all C#-Everything packages require the everything service running on the system. Either started by the user as a process (see below), or by the service being installed in the system.

I don't know the internal workings of Everything. My understanding is, it accesses NTFS meta data very low level to quickly gather the information it requires to build up it's search index. I am not sure if that is even possible from managed code. If you are interested, I suggest you contact the developer of Everything directly: https://www.voidtools.com/contact/

For the scenarios I am aiming for, it is sufficient to assume that the Everything service is already installed, since I am targetting for tools for developers. And Everything is awesome.

If you want to bundle Everything with your application, you can spawn it as user processes if there is no service running, and be independent from any installation needs. This is sort of what I am doing for running my tests in the Github Actions: https://github.com/sgrottel/EverythingSearchClient/blob/main/.github/workflows/dotnet-desktop.yml#L28

I have no plans to extend this project beyond being an access library to the IPC API of Everything.
